### ISSUE TITLE
possible security issue

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/omniauth-saml-va#16]
https://duo.com/blog/duo-finds-saml-vulnerabilities-affecting-multiple-implementations

Basically, comments in XML have some fun with SAML. Might want to check the internal SSO bits to see if this impacts this usage of ruby-saml

**Comment by evankroske** [comment]
Thanks for pointing this out! We've already addressed the issue:

https://github.com/department-of-veterans-affairs/omniauth-saml-va/pull/15
