### ISSUE TITLE
License in the gemspec isn't correct

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/omniauth-saml-va#5]
This isn't MIT, it's not clear to me we can even legally make something MIT.

**Comment by paultag** [comment]
Doh. Copy paste fail. I put PD In the readme.

Legally that'd only apply outside the US, but CC0 is  bit more clear for
international use.

**Comment by alex** [comment]
We should take a look at what 18f does for their gems, they've got a pretty standard license block.

**Comment by paultag** [comment]
Yeah, I took that README block from 18F; I updated the License information to be CC0

Pushed as https://github.com/department-of-veterans-affairs/omniauth-saml-va/commit/006b8aecb516efd5fc63edbf77b70833457b8f42

Good to close?

**Comment by alex** [comment]
lgtm

On Sun, Oct 11, 2015 at 8:51 AM, notifications@github.com wrote:

> Yeah, I took that README block from 18F; I updated the License information
> to be CC0
> 
> Pushed as 006b8ae
> https://github.com/department-of-veterans-affairs/omniauth-saml-va/commit/006b8aecb516efd5fc63edbf77b70833457b8f42
> 
> Good to close?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/department-of-veterans-affairs/omniauth-saml-va/issues/5#issuecomment-147212660
> .

## 

"I disapprove of what you say, but I will defend to the death your right to
say it." -- Evelyn Beatrice Hall (summarizing Voltaire)
"The people's good is the highest law." -- Cicero
GPG Key fingerprint: 125F 5C67 DFE9 4084
